image:
  file: .gitpod.Dockerfile
  
# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: 
    # command: echo 'start script'

vscode:
  extensions:
    - Ionide.Ionide-fsharp
    # https://open-vsx.org/extension/muhammad-sammy/csharp - the microsoft one isnt on there, i guess this guy ported it to open-vsx.org
    - muhammad-sammy.csharp
